"""empty message

Revision ID: 212a16607095
Revises: 093d92ab3825
Create Date: 2024-02-13 13:15:51.123287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212a16607095'
down_revision = '093d92ab3825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franchises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('franchise_no', sa.Integer(), nullable=True),
    sa.Column('date_opened', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_franchises')),
    sa.UniqueConstraint('branch_name', name=op.f('uq_franchises_branch_name'))
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('hiring_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], name=op.f('fk_employees_franchise_id_franchises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('franchises')
    # ### end Alembic commands ###
